[versions]
asm = "9.4"
jackson = "2.15.0"
junit5 = "5.8.1"
spock = "2.1-groovy-3.0"

[libraries]
ant = "org.apache.ant:ant:1.10.12"
antlrst4 = "org.antlr:ST4:4.3.4"
apache-compress = "org.apache.commons:commons-compress:1.21"
apache-rat = "org.apache.rat:apache-rat:0.11"
asm = { group = "org.ow2.asm", name="asm", version.ref="asm" }
asm-tree = { group = "org.ow2.asm", name="asm-tree", version.ref="asm" }
bytebuddy = "net.bytebuddy:byte-buddy:1.12.10"
checkstyle = "com.puppycrawl.tools:checkstyle:10.3"
commons-codec = "commons-codec:commons-codec:1.11"
commmons-io = "commons-io:commons-io:2.2"
docker-compose = "com.avast.gradle:gradle-docker-compose-plugin:0.16.12"
forbiddenApis = "de.thetaphi:forbiddenapis:3.5.1"
hamcrest = "org.hamcrest:hamcrest:2.1"
httpcore = "org.apache.httpcomponents:httpcore:4.4.12"
httpclient = "org.apache.httpcomponents:httpclient:4.5.10"
idea-ext = "gradle.plugin.org.jetbrains.gradle.plugin.idea-ext:gradle-idea-ext:1.1.4"
json-schema-validator = "com.networknt:json-schema-validator:1.0.72"
json-assert = "org.skyscreamer:jsonassert:1.5.0"
jackson-core = { group = "com.fasterxml.jackson.core", name="jackson-core", version.ref="jackson" }
jackson-databind = { group = "com.fasterxml.jackson.core", name="jackson-databind", version.ref="jackson" }
jackson-dataformat-yaml = { group = "com.fasterxml.jackson.dataformat", name="jackson-dataformat-yaml", version.ref="jackson" }
jackson-platform = { group = "com.fasterxml.jackson", name="jackson-bom", version.ref="jackson" }
jna = "net.java.dev.jna:jna:5.10.0"
junit = "junit:junit:4.13.2"
junit5-platform = { group = "org.junit", name="junit-bom", version.ref="junit5" }
junit5-jupiter = { group = "org.junit.jupiter", name="junit-jupiter", version.ref="junit5" }
junit5-platform-launcher = "org.junit.platform:junit-platform-launcher:1.8.1"
junit5-vintage = { group = "org.junit.vintage", name="junit-vintage-engine", version.ref="junit5" }
maven-model = "org.apache.maven:maven-model:3.6.2"
mockito-core = "org.mockito:mockito-core:1.9.5"
nebula-info = "com.netflix.nebula:gradle-info-plugin:11.3.3"
shadow-plugin = "com.github.johnrengelman:shadow:8.1.1"
spock-core = { group = "org.spockframework", name="spock-core", version.ref="spock" }
spock-junit4 = { group = "org.spockframework", name="spock-junit4", version.ref="spock" }
spock-platform = { group = "org.spockframework", name="spock-bom", version.ref="spock" }
spotless-plugin = "com.diffplug.spotless:spotless-plugin-gradle:6.18.0"
wiremock = "com.github.tomakehurst:wiremock-jre8-standalone:2.23.2"
xmlunit-core = "org.xmlunit:xmlunit-core:2.8.2"
